export const GET_USER = 'GET_USER';
export const LOG_IN = 'LOG_IN';
export const GET_CONTACTS_SUCCESSFULLY = 'GET_CONTACTS_SUCCESSFULLY';
// export const GET_CONTACTS = 'GET_CONTACTS';
export const DELETE_CONTACT_SUCCESSFULLY = 'DELETE_CONTACT_SUCCESSFULLY';
export const EDIT_CONTACT_SUCCESSFULLY = 'EDIT_CONTACT_SUCCESSFULLY';
export const CREATE_CONTACT_SUCCESSFULLY = 'CREATE_CONTACT_SUCCESSFULLY';
